service:
  name: watchfacemarket

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      pool-name: marketHikariCP
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://db_mysql_app_0.uc.mobvoi-idc.com/appstore_awch?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&useUnicode=true&serverTimezone=GMT%2B8
      username: appstore_awch
      password: GHd8QtBwzgmc7sdv
      connection-test-query: SELECT 1
      idle-timeout: 30000
      connection-timeout: 30000

    druid:
      initial-size: 5
      min-idle: 5
      max-active: 40
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.next.watchfacemarket.dto.po